### ISSUE TITLE
Does not work with re3

### ISSUE THREAD

**Issue by ronangaillard** [cleolibrary/III.VC.CLEO#14]
Hi,

I did not manage to info on the internet but is CLEO supposed to work with re3 ?

I'm using re3 on MacOS to play GTA3, but I did not manage to use CLEO and plugins.

Thanks :)

**Comment by x87** [comment]
Hi,

Not this, but there is another version of CLEO that supports re3/reVC
https://github.com/cleolibrary/CLEO-Redux

It's unlikely to work on MacOS though: https://github.com/cleolibrary/CLEO-Redux#compatibility-with-re3-and-revc
