### ISSUE TITLE
关于cleo v1.1.1.7 可以支持无名汉化补丁的外接文本而 v2.0.0.6 不能外接中文的问题

### ISSUE THREAD

**Issue by Lzh102938** [cleolibrary/III.VC.CLEO#16]
当使用[2.【GTAVC罪恶都市汉化补丁】wm_vcchs_Koishi_1.0_Build161113.zip](https://github.com/cleolibrary/III.VC.CLEO/files/11592869/2.GTAVC.wm_vcchs_Koishi_1.0_Build161113.zip)时，使用cleo的1.1.1.7版本可以外接文本fxt显示中文，但v2.0.0.6却不能了，这是为什么？这是汉化补丁的源代码
<https://github.com/R-YaTian/LC.VC.SA.Plugin>，能否使得最新版的cleo主程序能够外接中文呢？

**Comment by x87** [comment]
English, pleasd

**Comment by Lzh102938** [comment]
May I ask if Cleo in v1.1.1.7 supports inserting fxt into Japanese, and then v2.0.0.6 cancels Japanese support? Is that the case? If so, can we add support for Japanese again? Our Chinese version of the game patch requires fxt to insert Chinese, and the Cleo main program in v1.1.1.7 supporting Japanese may be one of the reasons for inserting Chinese

**Comment by XMDS** [comment]
@Lzh102938  cleo库的`CustomText::GetText`的处理有问题，cleo库对游戏原始的`GetText`函数做了hook操作，以便在获取文本时，能够找到外部的fxt文件(key+ text格式)，并读取文本，代码在找不到key对应的文本时(例如游戏main使用来自于gxt的文本)，会回调游戏原来的GetText函数，这样游戏按原来的形式读取文本(无论它是什么语言)，但如果读到fxt中的key，只执行cleo库自己的文本操作，它不在回调原函数，自然不在处理日语和俄语。
简单来讲，文件内容以key+text格式形成，在游戏获取文本时，gxt里的仍然走游戏自己的，fxt的走cleo库的，但cleo库没有处理额外的.
我不清楚无名汉化组是否对游戏CText类有过更改，但只从代码来看，可能猜测是这样，也许我有时间可以更新cleo库试试.但我现在重心在安卓

**Comment by XMDS** [comment]
@Lzh102938  v2.0.0.7-pre 已修复 您可以测试一下：
VC.CLEO.…
链接:https://pan.baidu.com/s/1SYlh9VI1USwaZhFt2b15tg 
提取码:bh34

**Comment by Tommy882** [comment]
> @Lzh102938 v2.0.0.7-pre 已修复 您可以测试一下： VC.CLEO.… 链接:[https://pan.baidu.com/s/1SYlh9VI1USwaZhFt2b15tg ](https://pan.baidu.com/s/1SYlh9VI1USwaZhFt2b15tg%C2%A0) 提取码:bh34

大佬辛苦了

**Comment by XMDS** [comment]
新版已经支持中文fxt
