### ISSUE TITLE
Support fixed-length strings

### ISSUE THREAD

**Issue by x87** [cleolibrary/III.VC.CLEO#29]
https://github.com/cleolibrary/III.VC.CLEO/blob/01684d76355fe28ccf33c7e1b77582d595d262a9/source/III.VC.CLEO/CustomScript.cpp#L231-L233

Instead of `break`, this code indicates a start of a new fixed length (up to 7 characters + zero bytes; 8 in total) character array.

This will allow code like

```
0AAB: '1.txt'
```

**Comment by ByHatcker** [comment]
`cpp`void CScript::ReadShortString(char *out)
{
    strncpy(out, &game.Scripts.Space[this->m_dwIp], 7);
    out[7] = '\0';
    this->m_dwIp += 8;
    return; // Вместо break
}
``

**Comment by ByHatcker** [comment]
`void CScript::ReadShortString(char *out)
{
    strncpy(out, &game.Scripts.Space[this->m_dwIp], 7);
    out[7] = '\0';
    this->m_dwIp += 8;
    return; // Вместо break
}
`

**Comment by XMDS** [comment]
VC short string (8 bytes) exists in the original game, such as 03A4 SCRIPT_NAME, but there is no "type value", and it makes no sense to add a separate type.

**Comment by x87** [comment]
Try to compile 0AAB: '1.txt' and run on current CLEO

**Comment by XMDS** [comment]
ok Fixed
