### ISSUE TITLE
0340: [GTA III]

### ISSUE THREAD

**Issue by mfisto** [cleolibrary/III.VC.CLEO#5]
Нашел еще одну странность. То ли это баг R\* то ли клео, вообщем. Если написать 0340: set_text_draw_color 0 0 0 255, т.е. какой либо из параметров = 0, то текст просто пропадает.

**Comment by x87** [comment]
Надо проверить main.scm без CLEO, если не будет показываться, значит проблема у R*

**Comment by mfisto** [comment]
Причем надо проверить мейн измененный, поскольку этот опкод не применялся практически в III части.

**Comment by mfisto** [comment]
Я проверил на стандартном мейне без CLEO, такая же ерундень, походу.
