### ISSUE TITLE
[III] Opcode 0ADD bug

### ISSUE THREAD

**Issue by spaceeinstein** [cleolibrary/III.VC.CLEO#9]
The opcode can only successfully spawn the Rhino and using model indexes 128 and above crashes the game.

**Comment by ThirteenAG** [comment]
Opcode replaces rhino ID and then calls cheat function, then restores the id.
https://github.com/cleolibrary/III.VC.CLEO/blob/master/source/III.VC.CLEO/CustomOpcodes.cpp#L1869
Is something wrong with the code or the game can't spawn cars with that function?
I can't check now, will do it later.

**Comment by spaceeinstein** [comment]
At address 0x490F13, the game checks if the Rhino model is loaded. The code didn't make the change to account for other models. Addresses 0x490F02 and 0x490F85 represent the model index of the vehicle but the game interprets it as a signed value. Any model indexes 0x80 and above are interpreted as negative by the game and results in a crash.
